Repository BoevaLab/CanSig, pull requests merged in 2022-05, with the labels that each got.

#12 Preprocessing tutorial
  cansig/tutorial.py
  docs/preprocessing.rst
  setup.cfg
Labels: documentation

#14 Add GitHub link
  docs/conf.py
Labels: documentation

#13 Data downloading function
  cansig/tutorial.py
Labels: enhancement

#15 CanSig alpha version
  .github/workflows/build.yml
  README.md
  cansig/api.py
  cansig/cluster/__init__.py
  cansig/cluster/api.py
  cansig/cluster/leiden.py
  cansig/filesys.py
  cansig/gsea.py
  cansig/interface/__init__.py
  cansig/interface/cluster.py
  cansig/metaanalysis/__init__.py
  cansig/metaanalysis/heatmap.py
  cansig/models/__init__.py
  cansig/models/api.py
  cansig/models/scvi.py
  cansig/run/integration.py
  cansig/run/pipeline.py
  cansig/run/postprocessing.py
  cansig/run/summary.py
  docs/index.rst
  requirements.txt
  setup.cfg
  tests/cluster/test_leiden.py
  tests/models/test_scvi.py
  tests/test_filesys.py
Labels: enhancement

#26 Fix bug with GSEA initialization
  cansig/cluster/leiden.py
  cansig/run/postprocessing.py
Labels: bug

#38 Differential CNV analysis
  cansig/cnvanalysis/__init__.py
  cansig/cnvanalysis/differentialcnvs.py
  cansig/filesys.py
  cansig/gsea.py
  cansig/run/pipeline.py
  cansig/run/postprocessing.py
  requirements.txt
  setup.cfg
Labels: enhancement

#40 Fix heatmap resolution
  cansig/metaanalysis/heatmap.py
  cansig/run/pipeline.py
Labels: bug

#39 Download the tutorial dataset
  cansig/run/download.py
Labels: enhancement
